services:
  - type: web
    name: anomia-llm-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        value: 3001
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FRONTEND_URL
        value: https://carriee-liuu.github.io/anomia-llm
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

