# Railway Configuration
# This file tells Railway how to deploy your Python backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = 3001
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"